version: "3.8"
services:
  videoroom_advanced:
    image: membraneframework/demo_webrtc_videoroom_advanced:latest
    environment:
      VIRTUAL_HOST: "videoroom.membraneframework.org"
      LETSENCRYPT_HOST: "videoroom.membraneframework.org"
      USE_INTEGRATED_TURN: "false"
      INTEGRATED_TURN_IP: "135.181.203.255"
      INTEGRATED_TURN_PORT_RANGE: "50000-50500"
    ports: 
      - "50000-50500:50000-50500/tcp"
      - "50000-50500:50000-50500/udp"
      
  
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-data:
  
