version: '3.1'

services:
  asterisk:
    image: dougbtv/asterisk
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/sounds:/var/lib/asterisk/sounds
      - ./asterisk/recordings:/var/spool/asterisk/monitor
    ports:
      - 5061:5061/udp
      - 5061:5061/tcp
      - "10000-10100:10000-10100/udp"
    environment:
      # add your environment variables here
      - EXTERNAL_IP=$EXTERNAL_IP
      - LOCAL_NET=${LOCAL_NET:-$EXTERNAL_IP/24}
    container_name: my-asterisk
    entrypoint: [ "/etc/asterisk/startup.sh" ] # replace "command" with "entrypoint"
